// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD4OWezjPGXRz3EqCF8-X6i_X6c-vtpqc',
    appId: '1:1023680758521:android:5dcea7a962cbb70ac45828',
    messagingSenderId: '1023680758521',
    projectId: 'healthonify-7506a',
    storageBucket: 'healthonify-7506a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArNhzOaHObh1qBm3piYa1KWYIr2oW1wI0',
    appId: '1:1023680758521:ios:68cf8918eb5e18d6c45828',
    messagingSenderId: '1023680758521',
    projectId: 'healthonify-7506a',
    storageBucket: 'healthonify-7506a.appspot.com',
    androidClientId: '1023680758521-04iekjoh52o92ftqdhe9h01891i26s8h.apps.googleusercontent.com',
    iosClientId: '1023680758521-2b1culr9k9jocebjnc3pd0gv6f4ord0d.apps.googleusercontent.com',
    iosBundleId: 'com.octal.healthonify',
  );
}
